### ISSUE TITLE
Memory leaks using SharedNetwork projections

### ISSUE THREAD

**Issue by otonck** [Repast/repast.hpc#10]
Hello Repast.HPC dev team,

we experienced some quite important memory leaks using Repast.HPC with a SharedNetwork projection. Each call to synchronizeProjectionInfo led to more memory being leaked, resulting to a huge memory consumption in our scenario.

After some valgrind analysis, we could identify and fix the issue :

1. The clear() method of the classes ImporterSet, ImporterMap, etc... clears the "sources" map without deleting the items inside it first : https://github.com/Repast/repast.hpc/blob/7c0316741e9f3f04b98a9b957c1bdeb808e62ef5/src/repast_hpc/AgentImporterExporter.h#L491 (note that the items deletion is appropriately done in those classes destructors, but is probably missing in the clear() methods)
2. The getProjectionInfo method also seems to leak memory when a non null but empty ProjectionInfoPacket pointer is returned here : https://github.com/Repast/repast.hpc/blob/7c0316741e9f3f04b98a9b957c1bdeb808e62ef5/src/repast_hpc/Projection.h#L309 (a new ProjectionInfoPacket object is instanciated and its pointer is lost if isEmpty() is true since its not added to the "packet" vector in this case)

I can prepare a PR if you like.

Thank you very much for your great work on this project !

**Comment by ncollier** [comment]
@otonck Thanks for the bug report. A PR would be most appreciated.

**Comment by otonck** [comment]
Thank you. I made a quick PR here : https://github.com/Repast/repast.hpc/pull/11

**Comment by ncollier** [comment]
Fixed with PR merge in [a96c15f](https://github.com/Repast/repast.hpc/commit/a96c15f99589d15352523a0a710362af8997852a)
