### ISSUE TITLE
When using SharedSpaces, the last state of the agent is not updated in the move

### ISSUE THREAD

**Issue by martinparadiso** [Repast/repast.hpc#4]
# Summary

Hello, I am currently working on a simulation using this framework, and I have encounter some strange behavior when the agents *walk* between processes which I believe is a bug.

The strange behavior happens when using a SharedDiscreteSpace (but probably happens with continuous spaces too), and the agent moves to the adjacent process where he previously existed as a non-local copy. As far as I can tell, the last internal state of the Agent is not updated.

# Environment

* OS: Ubuntu 20.04
* Library version: the included in dist/Manual/Typical, but happens with updated libraries too.

# Steps to reproduce

Walk an agent from one process to another and when moved to another process inspect it's internal state. I made a small program to demonstrate the bug:

I have modified the Demo_03 of the tutorial, keeping only one agent and changing it's behavior. The agent simply walks in a discrete space from point [0, 4] to point [9, 4]. The agent also has an internal counter that is incremented once by tick, and on each execution prints the current value and the incremented value.

The source is in this repository: https://github.com/martinparadiso/repast.hpc-bugdemo. I created two Docker images, the original version and a "fixed" version using a modified fork of this repository.

# Expected result

The image `ghcr.io/martinparadiso/repast.hpc-bugdemo-patched:latest` is the expected output, the code was compiled using a modified version of repast.hpc (more on that later).

```
$ docker run ghcr.io/martinparadiso/repast.hpc-bugdemo-patched
AgentId(0, 0, 0, 0)@0, tick=2, counter 0 -> 1
AgentId(0, 0, 0, 0)@0, tick=3, counter 1 -> 2
AgentId(0, 0, 0, 0)@0, tick=4, counter 2 -> 3
AgentId(0, 0, 0, 0)@0, tick=5, counter 3 -> 4
AgentId(0, 0, 0, 0)@0, tick=6, counter 4 -> 5
AgentId(0, 0, 0, 2)@2, tick=7, counter 5 -> 6
AgentId(0, 0, 0, 2)@2, tick=8, counter 6 -> 7
AgentId(0, 0, 0, 2)@2, tick=9, counter 7 -> 8
AgentId(0, 0, 0, 2)@2, tick=10, counter 8 -> 9
```

# Actual Result

But if you run the image `docker run ghcr.io/martinparadiso/repast.hpc-bugdemo:latest` which uses the version in this repository, the output is the following:

```
$ docker run ghcr.io/martinparadiso/repast.hpc-bugdemo
AgentId(0, 0, 0, 0)@0, tick=2, counter 0 -> 1
AgentId(0, 0, 0, 0)@0, tick=3, counter 1 -> 2
AgentId(0, 0, 0, 0)@0, tick=4, counter 2 -> 3
AgentId(0, 0, 0, 0)@0, tick=5, counter 3 -> 4
AgentId(0, 0, 0, 0)@0, tick=6, counter 4 -> 5
AgentId(0, 0, 0, 2)@2, tick=7, counter 4 -> 5
AgentId(0, 0, 0, 2)@2, tick=8, counter 5 -> 6
AgentId(0, 0, 0, 2)@2, tick=9, counter 6 -> 7
AgentId(0, 0, 0, 2)@2, tick=10, counter 7 -> 8

```

As you can see, the counter is incremented from 4 to 5 two times. And if you check the `currentRank` value of the ID you will see that the first increment happens in the process 0, and the second one in the process 2. This led me to believe that the last internal state of the agent was not synchronized.

# Inspection

Upon inspection with GDB, I tracked down the problem to this line, in `RepastProcess.hpp:1113` (https://github.com/Repast/repast.hpc/blob/master/src/repast_hpc/RepastProcess.h#L1113), in the Step 10 of `synchronizeAgentStatus(...)`:

```c++
	// STEP 10: Insert the newly received agents that moved to this process and update exporters
	typename std::vector<SyncStatus_Packet<Content>*>::iterator packetIter;
	typename std::vector<SyncStatus_Packet<Content>*>::iterator packetIterEnd =
			packetsRecd.end();
	AgentRequest secondaryAgentsToRequest(rank_);
	for (packetIter = packetsRecd.begin(); packetIter != packetIterEnd;
			++packetIter) {
		std::vector<Content>* content = (*packetIter)->agentContentPtr;
		typename std::vector<Content>::iterator contentIter = content->begin();
		while (contentIter != content->end()) {
			T* out = creator.createAgent(*contentIter);
			T* inContext = context.addAgent(out);
			if (inContext != out) { // Already contain the agent
				// If the agent is local on this rank, do nothing (the agent received must be a secondary agent)
				// If the agent is non-local on this rank
/*LINE 1113*/			if (inContext->getId().currentRank() != rank_) {
					// If the arriving agent has a current rank equal to this rank, this
					// is an incoming, newly arrived local agent that already existed on this
					// process as a secondary agent; it should be updated and its currentRank in
					// its ID set to the local rank
					if (out->getId().currentRank() == rank_) {
						updater.updateAgent(*contentIter);
						inContext->getId().currentRank(rank_);
					}
					// Otherwise, it's a secondary agent arriving from another process, when it
					// already exists as a non-local agent on this process; leave the original alone
					// and discard the new version.
				}
				delete out;
			} else { // Agent was not already on this rank and is not a new local agent; must process it as a new request
				if (out->getId().currentRank() != rank_)
					secondaryAgentsToRequest.addRequest(out->getId());
			}
			contentIter++;
		}

		// Update the importer/exporter to reflect the newly arrived local agents
		importer_exporter->incorporateAgentExporterInfo(
				*((*packetIter)->exporterInfoPtr));
		importer_exporter->clearExportToSpecificProc(rank_); // Export Info may include 'exports' to self; remove these

	}
```

If I understand the comments correctly, the scenario of "transfering the ownership of an agent that previously existed as a non-local copy" if covered here. 

The line `if (inContext->getId().currentRank() != rank_)` checks if the agent in the local context is *currently* a non-local copy, hence the `!= rank_`, which is the scenario fo agents walking past the process boundaries. If the agent is non-local, and the incoming, updated agent is assigned to this process (the line `if (out->getId().currentRank() == rank_) {`), the framwork correctly updates the internal states and assigned the new `currentRank`.

The problem is that last part doesn't happen. Inspecting the values with a debugger will show that the ID of the agent is already updated to match `currentRank = rank_` when the program evaluates `if (inContext->getId().currentRank() != rank_)`, so the update never happens.

Upon further inspection I found that the `currentRank` is previously updated in `RepastProcess.h:927`, https://github.com/Repast/repast.hpc/blob/master/src/repast_hpc/RepastProcess.h#L927, in the first step of `synchronizeAgentStatus(...)`:

```c++
	// Step 1: Exchange information about agents whose status will be updated.
	//
	// Status Updates have been added to the importer_exporter and can now be exchanged
	// across processes. All processes will now know that an agent that has previously
	// been managed by process A will either be eliminated from the simulation or
	// moved to process B.
	std::vector<std::vector<AgentStatus>*> statusUpdates;
	importer_exporter->exchangeAgentStatusUpdates(*world, statusUpdates);

	for (size_t i = 0, n = statusUpdates.size(); i < n; i++) {
		std::vector<AgentStatus>* vec = statusUpdates[i];
		for (size_t j = 0, k = vec->size(); j < k; ++j) {
			AgentStatus& status = (*vec)[j];
			if (status.getStatus() == AgentStatus::REMOVED) {
				importer_exporter->importedAgentIsRemoved(status.getOldId()); // Notify importer/exporter that this agent will not be imported anymore
				context.importedAgentRemoved(status.getOldId()); // Remove from context; agent cannot exist on this process after removal from home process
			} else if (status.getStatus() == AgentStatus::MOVED) {
				if (rank_ != status.getNewId().currentRank()) {
					// Notify importer that this agent will not be imported from the original
					// process, but will instead be imported from its new home
					importer_exporter->importedAgentIsMoved(status.getOldId(),
							status.getNewId().currentRank());
				} else {
					// Notify importer that the agent will not be imported anymore because this is its home process now
					importer_exporter->importedAgentIsNowLocal(
							status.getOldId());
				}
				// Find it and update its id
				T* agent = context.getAgent(status.getOldId());
				if (agent == (void*) 0)
					throw Repast_Error_32<AgentId>(status.getOldId()); // Agent not found
/*LINE 927*/			agent->getId().currentRank(status.getNewId().currentRank());
			}
		}
		delete vec;
	}
```

The line 927 (`agent->getId().currentRank(status.getNewId().currentRank());`) inconditionally updates all agents in the context to match the new `currentRank`. This means that, when Step 10 checks if the agent is non-local, will return false because it is already updated to match this rank.

# Patch

I have forked this repo and applied a patch based on the previous analysis. So, if the analysis is wrong, the patch is wrong too. I modified the Step 1 to update only agents that are not moving into this process:

```
diff --git a/src/repast_hpc/RepastProcess.h b/src/repast_hpc/RepastProcess.h
index e23f897..19d04e1 100644
--- a/src/repast_hpc/RepastProcess.h
+++ b/src/repast_hpc/RepastProcess.h
@@ -920,11 +920,13 @@ void RepastProcess::synchronizeAgentStatus(SharedContext<T>& context,
                                        importer_exporter->importedAgentIsNowLocal(
                                                        status.getOldId());
                                }
-                               // Find it and update its id
-                               T* agent = context.getAgent(status.getOldId());
-                               if (agent == (void*) 0)
-                                       throw Repast_Error_32<AgentId>(status.getOldId()); // Agent not found
-                               agent->getId().currentRank(status.getNewId().currentRank());
+                               // If the agent is not moving into this process, find it and update its id
+                               if (rank_ != status.getNewId().currentRank()) {
+                                       T* agent = context.getAgent(status.getOldId());
+                                       if (agent == (void*) 0)
+                                               throw Repast_Error_32<AgentId>(status.getOldId()); // Agent not found
+                                       agent->getId().currentRank(status.getNewId().currentRank());
+                               }
                        }
                }
                delete vec;
```

As mentioned in the Expected Behavior section, the Docker image using this patched version is `ghcr.io/martinparadiso/repast.hpc-bugdemo-patched`, which uses the forked/patched version, and correctly increments the value:

```
$ docker run ghcr.io/martinparadiso/repast.hpc-bugdemo-patched
AgentId(0, 0, 0, 0)@0, tick=2, counter 0 -> 1
AgentId(0, 0, 0, 0)@0, tick=3, counter 1 -> 2
AgentId(0, 0, 0, 0)@0, tick=4, counter 2 -> 3
AgentId(0, 0, 0, 0)@0, tick=5, counter 3 -> 4
AgentId(0, 0, 0, 0)@0, tick=6, counter 4 -> 5
AgentId(0, 0, 0, 2)@2, tick=7, counter 5 -> 6
AgentId(0, 0, 0, 2)@2, tick=8, counter 6 -> 7
AgentId(0, 0, 0, 2)@2, tick=9, counter 7 -> 8
AgentId(0, 0, 0, 2)@2, tick=10, counter 8 -> 9
```

# Final notes

Sorry for the verbosity, English is not my native language and I wanted to be as clear as posible. If the analysis/patch is correct I can create a pull request. Note that I didn't run the test suite and I'm unable to determine if this has more repercussions.

**Comment by ncollier** [comment]
Thanks for the bug report. We will look into it and let you know about the pull request.

**Comment by ncollier** [comment]
Applied patch. 19a62d9
