### ISSUE TITLE
Can't migrate Agents across processes using a SharedDiscreteSpace

### ISSUE THREAD

**Issue by PaulBreugnot** [Repast/repast.hpc#5]
Hello RepastHPC developers,

I am currently trying to implement a trivial distributed grid based model using Repast HPC 2.3.0, but I'm encountering distribution issues.

I am not sure the following problem is a bug: I am probably missing something, but I followed the tutorial several times, I read the API documentation, I tried several projects, and I still can't get it to work, so any help would be appreciated.

# Set Up
The complete project with build instructions is provided in [issue-00.zip](https://github.com/Repast/repast.hpc/files/6647721/issue-00.zip), but I'm going to illustrate key points here (the project is essentially based on the "Demo 03" of the tutorial).

I defined a grid and a context as follows in `DemoModel`:
```cpp
/* model.h */

class DemoModel {
    public:
        typedef repast::SharedDiscreteSpace<
            DemoAgent, repast::StrictBorders, repast::SimpleAdder<DemoAgent>
        > Grid;
    private:
        repast::SharedContext<DemoAgent> context;
        repast::Properties props;

        DemoAgentPackageProvider provider;
        DemoAgentPackageReceiver receiver;

        Grid* grid;
        ...
}
```
And the grid is initialized as follows in the DemoModel constructor:
```cpp
DemoModel::DemoModel(
		std::string prop_file, int argc, char** argv,
		boost::mpi::communicator* comm) :
	context(comm), props(prop_file, argc, argv), provider(context), receiver(context) {
		initializeRandom(props, comm);

		// Builds a grid so that each process is responsible for a
		// 2x3 local grid
		repast::Point<double> origin(0,0);
		repast::Point<double> extent(comm->size()*2, 3);

		// The grid is divided horizontally across processes
		std::vector<int> process_dims {comm->size(), 1};

		// Buffer size=1
		grid = new Grid("Grid", {origin, extent}, process_dims, 1, comm);
	
		std::cout <<
			"RANK " << repast::RepastProcess::instance()->rank() << std::endl <<
			"    GLOBAL BOUNDS: " << grid->bounds().origin() << "->" <<
			grid->bounds().extents() << std::endl <<
			"    LOCAL BOUNDS: " << grid->dimensions().origin() << "->" <<
			grid->dimensions().extents() << std::endl;

		context.addProjection(grid);
	}
```

Then I initialize a single agent at (0, 1):
```cpp
void DemoModel::init() {
	int rank = repast::RepastProcess::instance()->rank();
	repast::Point<int> new_location {0, 1};

	// Initializes a single agent on the process containing grid cell (0,1)
	if(grid->dimensions().contains(new_location)) {
		repast::AgentId id(0, rank, 0);
		id.currentRank(rank);
		DemoAgent* agent = new DemoAgent(id);

		context.addAgent(agent);
		grid->moveTo(agent, new_location);
	}

	this->synchronize();
}
```
This Agent just goes to the east until it reaches the border of the global grid:
```cpp
void DemoAgent::move(Grid* grid) {
	std::vector<int> location;
	grid->getLocation(this, location);
	location[0]++;

	if(grid->bounds().contains(location)) {
		grid->moveTo(this, location);
		std::cout <<
			this->getId() << " moves to (" << location[0] << "," << location[1] << ")"
			<< std::endl;
	}
}
```
The `DemoModel::synchronize()` method is implemented as follows, and called after each move:
```cpp
void DemoModel::synchronize() {
	std::cout << "Synchronizing model..." << std::endl;
	// Marks agents to move
	grid->balance();

	// Performs moves across processes
	repast::RepastProcess::instance()->synchronizeAgentStatus<
		DemoAgent, DemoAgentPackage, 
		DemoAgentPackageProvider, DemoAgentPackageReceiver>(
				context, provider, receiver, receiver
				);

	// Imports agent copies
	repast::RepastProcess::instance()->synchronizeProjectionInfo<
		DemoAgent, DemoAgentPackage,
		DemoAgentPackageProvider, DemoAgentPackageReceiver>(
				context, provider, receiver, receiver
				);

	// Updates agent copies
	repast::RepastProcess::instance()->synchronizeAgentStates<
		DemoAgentPackage, DemoAgentPackageProvider, DemoAgentPackageReceiver>(
				provider, receiver
				);
}
```

Unfortunately, the agent disappears when it reaches the border of the first process.

# Execution
See the included `README.md` file for detailed build an execution instructions.

`mpiexec -n 2 -output-filename out ./rhpc-issue ../props/config.props ../props/model.props`

#### Rank 0
`cat out/1/rank.0/stdout`
```
RANK 0
    GLOBAL BOUNDS: Point[0, 0]->Point[4, 3]
    LOCAL BOUNDS: Point[0, 0]->Point[2, 3]
Synchronizing model...

TICK 0
LOCAL AGENTS: 
AgentId(0, 0, 0, 0) at (0,1)
NON LOCAL AGENTS: 

AgentId(0, 0, 0, 0) moves to (1,1)
Synchronizing model...

TICK 1.2
LOCAL AGENTS: 
AgentId(0, 0, 0, 0) at (1,1)
NON LOCAL AGENTS: 

AgentId(0, 0, 0, 0) moves to (2,1)
Synchronizing model...

TICK 2.2
LOCAL AGENTS: 
NON LOCAL AGENTS: 

```
#### Rank 1
`cat out/1/rank.1/stdout`
```
RANK 1
    GLOBAL BOUNDS: Point[0, 0]->Point[4, 3]
    LOCAL BOUNDS: Point[2, 0]->Point[2, 3]
Synchronizing model...

TICK 0
LOCAL AGENTS: 
NON LOCAL AGENTS: 

Synchronizing model...

TICK 1.2
LOCAL AGENTS: 
NON LOCAL AGENTS: 
AgentId(0, 0, 0, 0) at (1,1)

Synchronizing model...

TICK 2.2
LOCAL AGENTS: 
NON LOCAL AGENTS: 

```
At `TICK 2.2`, I expect the agent to be a LOCAL agent on rank 1, but it simply disappears from the simulation.

Have a nice day and thank you for your time,

Paul

**Comment by ncollier** [comment]
I discussed this with one of the other developers and he pointed out that any 2D space needs at least 4 processes, and without that you can get some odd wrapping behavior where a rank is its own neighbor. This could be the cause of what you are seeing.

**Comment by PaulBreugnot** [comment]
I effectively noticed some crashes when using the `WrapAroundBorders` mode with only 2 processes, so I used the `StrictBorders` mode to simplify.
I'm going to make more tests with the `WrapAroundBorders` mode and 4 processes, to see if the issue persists.

**Comment by PaulBreugnot** [comment]
The issue is solved, it was my mistake.

I defined my Agent as follows:
```cpp
class DemoAgent {
	private:
		repast::AgentId id;

	public:
		DemoAgent(repast::AgentId id) : id(id) {}

		repast::AgentId getId() const {
			return id;
		}

		/**
		 * Updates the current rank of the agent.
		 */
		void updateAgent(int current_rank) {
			id.currentRank(current_rank);
		}
		...
};
```
I thought this `getId()` method was enough, since `updateAgent()` was used to update the agent `current_rank`.
But indeed, two `getId()` methods must be specified, as presented in the tutorial:
```cpp
class DemoAgent {
	private:
		repast::AgentId id;

	public:
		DemoAgent(repast::AgentId id) : id(id) {}

		repast::AgentId& getId() {
			return id;
		}

		const repast::AgentId& getId() const {
			return id;
		}

		/**
		 * Updates the current rank of the agent.
		 */
		void updateAgent(int current_rank) {
			id.currentRank(current_rank);
		}
		...
};
```
I guess repast HPC uses an `agent->getId().currentRank(rank)` call or something like that to update the agent rank when some migration is performed, what could not work with my implementation.

Sorry for the disagreement and thank you for the quick answer!
