### ISSUE TITLE
Segfault when calling SharedDiscreteSpace.balance

### ISSUE THREAD

**Issue by ncollier** [Repast/repast.hpc#8]
User reports issue when calling SharedDiscreteSpace.balance with process dims other than 2x2 and can reproduce in Tutorial Demo_03 Step_03. See https://stackoverflow.com/questions/71326034/running-discrete-grid-projections-on-more-than-4-processes/71341981#71341981

 I've been trying to reproduce by changing the process dimensions around line 95. For example,

```
processDims.push_back(2);
processDims.push_back(1);
```

And running with:

```
mpirun -n 2 ./Demo_03.exe ../../RepastHPC/Demo_03/Step_03/props/config.props  ../../RepastHPC/Demo_03/Step_03/props/model.props
```

I can't always reproduce it so I suspect it's linked to the random seed and the location of agents in the space, but a `global.random.seed = 2343` seems to trigger it with a dims of 4 and 2 and 8 ranks.

**Comment by ncollier** [comment]
In balance()

```c++
...
      if(!localBounds.contains(loc)){                            // If inside bounds, ignore
        Neighbor* ngh = nghs->findNeighbor(loc.coords());
        RepastProcess::instance()->moveAgent(id, ngh->rank());
      }
...
```
nghs->findNeighbor() is returning a null pointer, and then segfaul ton ngh->rank. 
For example when loc is ` {point = std::vector of length 2, capacity 2 = {-100, -2}, hash = 19571}` and current rank is 4. However, that location is in the rank 0 portion of the grid which is not a neighbor of 4.  

It's unclear how agent that can only move 1 unit at time can get from 4 to 0 in one movement.

**Comment by ncollier** [comment]
Possible problem in how agent's initial location is set in Demo_03_Model.init():

```c++
repast::Point<int> initialLocation((int)discreteSpace->dimensions().origin().getX() + i,(int)discreteSpace->dimensions().origin().getY() + i);
```
where i can be from 0 to 99. Depending on the world size and the number of ranks, an agent's initial location could be outside of the current rank (which is incoherent), and unit movement could then move it to a rank that is no longer a neighbor.  

That doesn't explain why there's an issue with process dimensions of (1, 2), but perhaps that's due to having self as a neighbor which I'm not sure is supported.

**Comment by SamGuard** [comment]
I am also having the exact same issue, when running with anything other than 2x2 processor dimension it will segfault when calling balance on the discrete space.

**Comment by A-Ruskov** [comment]
I attempted changing the initial locations, by just changing the number of agents from 99 to 15, and that did trigger the issue again, so I assume the issue is not related with the initialisation of the agents' locations.

**Comment by ncollier** [comment]
@SamGuard - Are you having the issue with the demo or with other code as well. If with other code, can you add some more details about your model?

**Comment by ncollier** [comment]
> I attempted changing the initial locations, by just changing the number of agents from 99 to 15, and that did trigger the issue again, so I assume the issue is not related with the initialisation of the agents' locations.

@A-Ruskov Are you setting a seed? What are you using for processDims? When I change the initial locations to be random within the space's local dimensions it no longer crashes for me.

**Comment by A-Ruskov** [comment]
@ncollier My fault, I am sorry, I hadn't stored the change to the count of agents correctly. Fixing the initial position works, the issue was indeed coming from initialising native agents in parts of the grid owned by other process which was not a neighbouring one. Thank you so much for the help.

**Comment by SamGuard** [comment]
> @SamGuard - Are you having the issue with the demo or with other code as well. If with other code, can you add some more details about your model?

My code is not the demo code but similar to it, it seems like I am doing the same thing as @A-Ruskov
